# :maple_leaf:错误与异常处理

<p id="title"></p>

## 目录点击链接
:point_right:<a href="#one" >1捕获异常<a><br>

:point_right:<a href="#two" >2.Dubug与调试<a><br>
 ***
<p id = "one"></p>  
  
## :four_leaf_clover:捕获异常 ##

使用try,catch,finally来捕获异常

* try块包含的代码组成了程序的正常操作部分，但这部分程序可能会有错误

* catch块包含的代码为处理各种错误的情况，这些错误是try中处理代码遇到的。

* finally块包含的代码清理资源或执行通常要在try块或catch块尾执行，无论是否有异常都要执行这个块

### 执行步骤 ###

(1)执行流程进入try块

(2)如果try中没有错误直接到达try尾部，如果有finally执行该块，一旦有错误，则try中程序会终止到达catch块，然后处理错误后再转到finally块

(3)在catch中处理错误

(4)执行catch不同的错误类型

(5)finally存在则执行该块

### 运行示例 ###

下面的示例是对用户输入的数字0~1000进行校检，针对错误进行的处理
```C#
            int k = 3;
            bool falg = true;
            while(falg)
            {
                if(k==0)falg = false;
                try{
                    string s;
                    Console.WriteLine("please input data:");
                    s = Console.ReadLine();
                    //是否为空
                    if(string.IsNullOrEmpty(s))
                    {
                        break;
                    }
                    //转换类型
                    int index = Convert.ToInt32(s);
      
                    if(index<0||index>1000)
                    {
                        //针对越界声明异常类型
                        throw new IndexOutOfRangeException($"你输入的数字:{s}越界(0~1000)");
                    }

                    Console.WriteLine($"你输入的数字: {index}");
                }
                //针对数字越界的错误执行的处理
                catch(IndexOutOfRangeException ex)
                {
                    Console.WriteLine(ex.Message);
                }
                //其余的错误处理
                catch(Exception ex)
                {
                    Console.WriteLine($"{ex.Message}");
                }
                finally
                {
                    Console.WriteLine("结束!");
                }
                k--;
            }
```

一开始程序进入try中如果一旦为空，break语句不止退出try块，还会退出while循环。 throw new IndexOutOfRangeException()是一个定义的异常类的构造函数该类
的参数为一个错误文本，所以下面catch中IndexOutOfRangeException ex是指try中对于这个index<0||index>1000不满足的错误返回的对象，Message是错误描述的
属性，如果错误不是由于我们规定的条件则返回的是Exception ex，它的Message属性是错误的原因，这个就不能是自己写的错误原因，而是返回系统编译的原因。

编译结果：

	please input data:
	256
	你输入的数字: 256
	结束!
	please input data:
	1556
	你输入的数字:1556越界(0~1000)
	结束!
	please input data:
	akfka
	Input string was not in a correct format.
	结束!
	
### System.Exception属性 ###

上面使用的只有Message属性，对于这个类还有其他的属性:

|属性|说明|
|:---:|:------|
|Data|这个属性可以给异常添加键/值语句，以提供关于异常的额外信息| 
|HelpLink|链接到一个帮助文件上，以提供关于该异常的更多信息|
|InnerException|如果此异常是在catch块中抛出，它就会把包含代码发送到catch中的异常对象|
|Message|描述错误的文本|
|Source|导致异常的应用程序名或对象名|
|StackTrace|栈上方法调用的详细信息，它有助于跟踪抛出异常的方法|


### 自定义编写异常错误 ###

我们也可以自己写异常处理类，如下这个类是对上面类的修改：

```C#
    class MyExceptionDispose : Exception
    {
    	//基类调用
        public MyExceptionDispose(string message) : base(message){
        }
	//声明错误代码
        public int ErrorCode{get;set;}
	//声明错误时间
        public DateTime DisposeTime;
    }
```

上面后要在主方法中调用：

```C#
     if(index<0||index>1000)
     {
          var MyException =new MyExceptionDispose($"你输入的数字:{s}越界(0~1000)");
          MyException.Source = "我的程序名";
          MyException.HelpLink = "file.txt";
          MyException.ErrorCode =404; 
          MyException.DisposeTime = DateTime.Now;
	  //抛出异常类
          throw MyException;
      }
```
像这样可以创立多个分支来为各种错误建立不同的处理方式。

 ***
<p id = "two"></p>  
  
## :four_leaf_clover:Dubug与调试 ##

在 C# 语言中允许在程序运行时输出程序的调试信息，类似于使用 Console.WriteLine 的方式向控制台输出信息。

所谓调试信息是程序员在程序运行时需要获取的程序运行的过程，以便程序员更好地解决程序中出现的问题，这种调试也被称为是非中断调试。

输出调试信息的类保存在 System.Diagnostics 命名空间中，通常用 Debug 类或 Trace 类实现调试时输出调试信息，具体的语句如下。

```C#
Debug.WriteLine();
Trace.WriteLine();
```

其中，Debug.WriteLine() 是在调试模式下使用的；Trace.WriteLine 除了可以在调试模式下使用，还可以用于发布的程序中。

下面通过实例来演示 Debug 类和 Trace 类的使用。

【实例】创建一个字符串类型的数组，在数组中存入从控制台输入的值，并输出每次向数组中存入的值。

```C#
class Program
{
    static void Main(string[] args)
    {
        string[] str = new string[5];
        Debug.WriteLine("开始向数组中存值：");
        for(int i = 0; i < str.Length; i++)
        {
            str[i] = Console.ReadLine();
            Debug.WriteLine("存入的第{0}个值为{1}", i, str[i]);
        }
        Debug.WriteLine("向数组中存值结束！");
    }
}
```

C# 语言中程序调试主要指在 Visual Studio 2017 中调试程序，包括设置断点、监视断点，以及逐语句、逐过程、使用一些辅助窗口来调试程序。

在 Visual Studio 2017 的菜单栏中单击“调试”，菜单项如下图所示。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z403100534133.gif)

其中列出的内容即为调试时可用的选项，下面介绍其常用的调试功能。

**1) 设置断点**

所谓断点是程序自动进入中断模式的标记，即当程序运行到此处时自动中断。

在断点所在行的前面用红色的圆圈标记，设置标记时直接用鼠标单击需要设置断点的行前面的灰色区域即可，或者直接按键盘上的 F9 键。

例如在程序中设置断点，效果如下图:

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z403100GI39.gif)


在设置断点时单击齿轮图标进入断点设置界面，如下图所示。

断点设置界面

在该界面中允许为断点设置条件或操作，条件是指在满足指定条件时才会命中该断点。

此外，每个断点也允许设置多个条件，每个条件之间的关系是“与”的关系。界面如下图所示。

断点设置中的条件设置

在设置条件时可以设置条件表达式、命中次数以及筛选器。

其中：
条件表达式是指一个布尔类型的表达式，如果满足条件则触发断点；
命中次数若满足指定次数，则触发断点；
筛选器用于限制只在某些进程和线程中设置断点。

在上图所示的界面中还可以为断点设置操作，用于指定在命中断点时打印追踪信息，界面如下图所示。

设置断点的操作界面

在该界面中，如果在“将消息记录到输出窗口”文本框中输出断点“string[] str = new string[5];”处，其中 str 的值，则可以写成“str={str}”的形式，在调试输出窗口中会发现“str=Null”的信息输出。

此外，右击断点，弹出的右键菜单如下图所示。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z40310121IZ.gif)

断点的右键菜单

在该菜单中选择“条件”或“操作”命令也可以完成对断点的上述设置。

**2) 管理断点**

在断点设置完成后，还可以在上图所示的菜单中选择进行“删除断点”“禁用断点”“编辑标签”“导出”的操作。

其中：
“删除断点”操作是取消当前断点，也可以再次单击断点的红点取消；
“禁用断点”操作是指暂时跳过该断点，将断点设置为禁用状态后，断点的右键菜单中的“禁用断点”选项更改为“启用断点”，在需要该断点时还可以选择“启用断点”恢复断点；
“编辑标签” 操作是为断点设置名称；
“导出”操作是将断点信息导出到一个 XML 文件中存放。

**3) 程序的调试过程**

在设置好断点后，调试程序可以直接按 F5 键，或者直接在菜单栏中选择“调试”→“开始调试”命令。

在调试程序的过程中，可以直接使用工具栏上的调试快捷键，如下图所示，或者直接在菜单栏中选择所需的调试命令。

调试快捷键菜单

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z403101JC14.gif)

下面介绍常用的调试命令。

* 逐语句（逐语句）：按 F11 键也可以，用于逐条语句运行。
* 逐过程（逐过程）：按 F10 键也可以，过程是指可以将方法作为一个整体去执行，不会跳进方法中执行。
* 跳出（跳出）：按 Shift+F11 组合键也可以，跳出是将程序的调试状态结束，并结束整个程序。

此外，在调试过程中右击，会出现如下图所示的右键菜单。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z40310201O36.gif)

调试过程中的右键菜单

在该菜单中也可以选择相应的命令实现调试功能。

在调试过程中经常使用该菜单中的“运行到光标处”命令将程序执行到指定的光标处，忽略程序中设置的断点，用于快速调试程序和定位可能出错的位置。

**4) 监视器**

在调试程序的过程中经常需要知道某些变量的值在运行过程发生的变化，以便发现其在何时发生错误。

将程序中的变量或某个表达式放入监视器中即可监视其变化状态。

假设将 for 循环中的循环变量 i 加入监视器，在程序中右击变量 i，在弹出的如上图所示的菜单中选择“添加监视”命令，效果如下图所示。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z403103540911.gif)

将变量 i 添加的监事器的效果

从上图中可以看出，在监视器界面的“名称”列中是变量名、“值”列中是当前变量 i 的值，“类型”列中是当前变量的数据类型。

在一个监视器中可以设置多个需要监视的变量或表达式。

对于监视器中不需要再监视的变量，可以右击该变量，在弹出的右键菜单中选择“删除监视”命令，如下图所示。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z40310232S36.gif)

操作监视器内容的右键菜单

此外，通过上图所示的菜单还可以进行编辑值、复制值、全部清除等操作。

**5) 快速监视**

在调试程序时，如果需要监视变量或表达式的值也可以使用快速监视。

例如仍然要监视变量 i 的值，右击变量 i，在弹出的右键菜单中选择“快速监视”命令，弹出如下图所示的对话框。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z403102424935.gif)

“快速监视器”对话框

通常，快速监视用于查看变量当前值的状态，与直接加入监视不同的是快速监视一次只能监视一个变量。

此外，在“快速监视”对话框处于打开状态时程序是无法继续调试的，如果需要继续监视“快速监视”对话框中的变量，可以单击“添加监视”按钮将当前监视的变量加入到监视器界面中。

**6) 即时窗口**

在调试程序时，如果需要对变量或表达式做相关运算，在即时窗口中都可以实现，并显示当前状态下变量或表达式的值。

在调试时可以使用“调试”菜单中“窗口”下的命令，在“调试”菜单中单击“窗口”出现如下图所示的子菜单。

“调试”菜单中的“窗口”子菜单

在其中选择“即时”命令即可出现即时窗口， 如下图所示。

![](http://c.biancheng.net/uploads/allimg/190403/4-1Z403102U0561.gif)

即时窗口

在即时窗口中输入变量 i 的值并按回车键，即出现当前 i 在程序运行到此时的值。
